### ISSUE TITLE
Chef won't point to correct git user's repo

### ISSUE THREAD

**Issue by avivroth** [rogueleaderr/definitive_guide_to_django_deployment#10]
Chef seems to insist on pointing to https://www.github.com/<my username> instead of https://www.github.com/rogueleaderr.  As such, the attempt to get the latest release from git times out.  Resetting the settings in settings.json did not correct the issue.  

The only way I could get chef to continue was to fork the django_deployment_example_project from rogueleaderr’s repo to mine.

**Comment by rogueleaderr** [comment]
I think you just need to put in your proper git username in the settings file creation and everything should be fine. Please reopen if you see again.
