### ISSUE TITLE
uninitialized constant Chef::Recipe::OpenSSLCookbook on fab create_instance:database

### ISSUE THREAD

**Issue by rossettistone** [rogueleaderr/definitive_guide_to_django_deployment#20]
When creating a new DB instance for the first time, I ran into the following error:

```
================================================================================
Recipe Compile Error in /home/ubuntu/chef-solo/cookbooks-2/django_application_server/recipes/database.rb
================================================================================


NameError
---------
uninitialized constant Chef::Recipe::OpenSSLCookbook


Cookbook Trace:
---------------
  /home/ubuntu/chef-solo/cookbooks-1/postgresql/recipes/server.rb:20:in `from_file'
  /home/ubuntu/chef-solo/cookbooks-2/django_application_server/recipes/database.rb:27:in `from_file'


Relevant File Content:
----------------------
/home/ubuntu/chef-solo/cookbooks-1/postgresql/recipes/server.rb:

 13:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 14:  # See the License for the specific language governing permissions and
 15:  # limitations under the License.
 16:  #
 17:
 18:  include_recipe "postgresql::ca_certificates"
 19:
 20>> ::Chef::Recipe.send(:include, OpenSSLCookbook::RandomPassword)
 21:
 22:  include_recipe "postgresql::client"
 23:
 24:  # randomly generate postgres password, unless using solo - see README
 25:  if Chef::Config[:solo]
 26:    missing_attrs = %w{
 27:      postgres
 28:    }.select do |attr|
 29:      node['postgresql']['password'][attr].nil?



[2015-12-17T03:29:37+00:00] ERROR: Running exception handlers
[2015-12-17T03:29:37+00:00] ERROR: Exception handlers complete
[2015-12-17T03:29:37+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated
[2015-12-17T03:29:37+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.

Fatal error: local() encountered an error (return code 100) while executing 'knife solo cook -i /project/django_deployment/deploy/ssh/markarossetti.pem ubuntu@ec2-54-200-157-236.us-west-2.compute.amazonaws.com ./nodes/database_node.json'

Aborting.
```

After some investigation, it turned out to be a change in a patch version of the postgresql cookbook that led to an incompatibility with the version of the openssl cookbook specified. I'll make a PR shortly with more details and a fix that worked for me. Just wanted to document this as an issue first.

**Comment by CloCkWeRX** [comment]
Can you report this upstream to the postgresql cookbook please.

**Comment by rogueleaderr** [comment]
Could you do it please? You're probably in a better position to give a detailed explanation of the problem.

Sent from Outlook for iPhone




On Thu, Mar 10, 2016 at 8:52 PM -0800, "CloCkWeRX" <notifications@github.com> wrote:












Can you report this upstream to the postgresql cookbook please.

**Comment by rossettistone** [comment]
Excellent idea. Reviewing this issue now though (it's been a few months!), I'm uncertain how it happened. The postgresql cookbook at 3.4.24 (https://github.com/hw-cookbooks/postgresql/blob/6584a0c05572b52992723705a4afc827e63016ba/metadata.rb) *does* specify openssl `~> 4.0`, which is correct. Somehow the berksfile in this repo took precedence with its `openssl 1.1` specification, and the conflict occurred. I'm puzzled, but I'm not sure if there's actually a problem in the postgresql cookbook.

If you can figure out what was going on here, I think you're absolutely right to report it in the postgresql cookbook repo!

**Comment by anshupitlia** [comment]
I'm facing a similar issue. Any insights?

**Comment by gjlondon** [comment]
Could you please write up a detailed explanation of the exact problem you're seeing and what triggers it?

Sent from Outlook for iPhone

On Thu, Apr 21, 2016 at 2:39 AM -0700, "anshupitlia" notifications@github.com wrote:

I'm facing a similar issue. Any insights?
