### ISSUE TITLE
settings.json can't be empty; must have valid json for suite to

### ISSUE THREAD

**Issue by avivroth** [rogueleaderr/definitive_guide_to_django_deployment#3]
While the README directs the reader to just "touch settings.json" before running the suite, it isn’t enough to get the suite running (it errors out).  Valid dummy JSON of some sort must be inserted into the file to prevent the suite from crashing.  Even just:

```json
{"dummyName" : "dummyValue"}
```
...will work.

**Comment by yourteamneedsadam** [comment]
Addressed in #14
