### ISSUE TITLE
Included Gemfile has dependency issues

### ISSUE THREAD

**Issue by avivroth** [rogueleaderr/definitive_guide_to_django_deployment#8]
The included Gemfile has dependency issues, and bundle does not successfully complete installation.  The error with bundle is:
```
Bundler could not find compatible versions for gem "json":
  In Gemfile:
    chef (~> 11.6.2) ruby depends on
      json (<= 1.7.7, >= 1.4.4) ruby

    berkshelf (~> 2.0.10) ruby depends on
      json (1.8.1)
```
However, installing each of the gems in the Gemfile manually with "gem install" works fine.

**Comment by rogueleaderr** [comment]
This should be fixed by #14 since you no longer need to install gems directly when we use Docker.
